[aws]
disabled = true

[character]
success_symbol = "[#](bold green)"
error_symbol   = "[#](bold red)"

[docker_context]
disabled = true

[java]
disabled = true

[kubernetes]
disabled = true

[package]
disabled = true

[terraform]
disabled = true
